### ISSUE TITLE
Missing pkg-config on OS X

### ISSUE THREAD

**Issue by itpetey** [netvl/ejdb.rs#5]
Another OS X issue: the Homebrew version of EJDB doesn't provide a pkg-config file, meaning that you either have to create your own or hack `build.rs`. A heuristic technique is probably appropriate for OS X as there are multiple potential package managers (Homebrew, MacPorts) or users may have compiled the lib themselves.

I'm happy to PR something more robust, though is it worth doing this check in the first place? If `libejdb.(so|dylib)` isn't installed then Rust will still refuse to compile.

For reference, here's my libejdb.pc:

```
prefix=/usr/local
exec_prefix=${prefix}
libdir=${exec_prefix}/lib
includedir=${prefix}/include
Name: libejdb
Version: 1.2.10
Description: EJDB
```

**Comment by netvl** [comment]
I don't really want to embed any heuristics to the build script. It is error-prone and not very portable, it increases maintenance burden without substantial benefits, given that this particular library has an official pkg-config file. If a package does not contain the pkg-config file, then it is very likely it is a mistake of the maintainer of said package. My suggested solution would be to ping the maintainer to fix this.

Actually, I've taken a look at the ejdb formula in homebrew and I see that it just invokes cmake and make install, and that's exactly what Arch's PKGBUILD from AUR does, but in the Arch's package the pc file is present:

```
% pacman -Ql libejdb | grep pc
libejdb /usr/lib/pkgconfig/libejdb.pc
% pkg-config --libs libejdb
-L/usr/lib64 -lejdb
```

This suggests that the pkg-config file is actually installed on your system; try to check for it again.

**Comment by itpetey** [comment]
Sorry for the late reply mate - been away overseas.

I double checked for `libejdb.pc` on a different machine with a clean build of EJDB and it doesn't exist anywhere (i.e. `sudo find / -name libejdb.pc` => nada). Definitely not being installed on either Yosemite or Sierra. I haven't tried debugging the Homebrew package so I'm not sure if this is intentional or not, though having read your reply I agree with you that it's the fault of the Homebrew package rather than the Rust binding.

Thanks as always for your thoroughness! :)
